export type EmployeeRecord = {
  id?: string
  employeeNumber: string
  employerFileNumber: string
  fullName: string
  initialsAndSurname: string
  firstNames: string
  idNumber: string
  taxNumber: string
  period: string
  employmentFrom: string
  employmentTo: string
  employerName: string
  employerTaxNumber: string
  postalAddress: string
  residentialAddress: string
  salariesWages: number
  commission: number
  freeHousing: number
  housingAllowance: number
  mortgageBondSubsidies: number
  entertainmentAllowance: number
  vehicleAllowance: number
  companyVehicleTaxValue: number
  travellingAllowance: number
  otherAllowance: number
  otherIncome: number
  grossPay: number
  taxableIncome: number
  paye: number
  pension: number
  totalDeductions: number
  medicalAid: number
  allowances: number
  pensionFundName: string
  providentFundName: string
  providentFundContribution: number
  retirementFundName: string
  retirementFundContribution: number
  assuranceCompanyName: string
  assuranceContribution: number
  spouse: string
  source: 'upload' | 'supabase'
}

export type SupabaseEmployeeRow = {
  id?: string
  user_id: string
  employee_number: string
  employer_file_number?: string
  full_name: string
  initials_and_surname?: string
  first_names?: string
  id_number: string
  tax_number: string
  period: string
  employment_from?: string
  employment_to?: string
  employer_name: string
  employer_tax_number: string
  postal_address?: string
  residential_address?: string
  salaries_wages?: number
  commission?: number
  free_housing?: number
  housing_allowance?: number
  mortgage_bond_subsidies?: number
  entertainment_allowance?: number
  vehicle_allowance?: number
  company_vehicle_tax_value?: number
  travelling_allowance?: number
  other_allowance?: number
  other_income?: number
  gross_pay: number
  taxable_income: number
  paye: number
  pension: number
  total_deductions?: number
  medical_aid: number
  allowances: number
  pension_fund_name?: string
  provident_fund_name?: string
  provident_fund_contribution?: number
  retirement_fund_name?: string
  retirement_fund_contribution?: number
  assurance_company_name?: string
  assurance_contribution?: number
  spouse?: string
}

